server:
  port: 8761

spring:
  application:
    name: opweEurekaServer
  datasource:
    username: postgres #developer01 #admin
    password: dev123456!
    url: jdbc:postgresql://101.200.41.70/opwe_main?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    hikari:
      #minimum idle time ,default 10，less than 0 or greater than maximum-pool-size will be reset to maximum-pool-siz
      minimum-idle: 2
      #less than or equal to 0 will be reset to default value of 10；greater than 0 and less than 1 will be reset to minimum-idle
      maximum-pool-size: 5
      max-lifetime: 300000
      idle-timeout: 180000
      connection-timeout: 30000
eureka:
  client:
    service-url:
      defaultZone: http://47.93.162.44:8761/eureka
    register-with-eureka: false
    fetch-registry: false
#logging:
#  level:
#    root: debug
