server:
  port: 8081

spring:
  application:
    name: opwe-open-service
  datasource:
    username: postgres #developer01 #admin
    password: dev123456!
    #    url: jdbc:mysql://database-1.cor1symsh3mv.ap-southeast-2.rds.amazonaws.com/inventory_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://101.200.41.70/opwe_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:postgresql://101.200.41.70/opwe_main?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    hikari:
      #minimum idle time ,default 10，less than 0 or greater than maximum-pool-size will be reset to maximum-pool-siz
      minimum-idle: 2
      #less than or equal to 0 will be reset to default value of 10；greater than 0 and less than 1 will be reset to minimum-idle
      maximum-pool-size: 5
      max-lifetime: 300000
      idle-timeout: 180000
      connection-timeout: 30000
  data:
    redis:
      host: 101.200.41.70
      port: 6379
      password: dev123456!
      lettuce:
        pool:
          max-idle: 8
          min-idle: 2
          max-wait: 1000
          max-active: 8
      timeout: 60s
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 101.200.41.70:8848
#      config:
#        file-extension: yaml
#        prefix: ${spring.application.name}
#        # dataID  ${prefix}-${spring.profiles.active}.${file-extension}
#        # 命名空间 默认 public
#        namespace: public
#        # 配置组  默认 DEFAULT_GROUP
#        group: opwe
  rabbitmq:
    host: 47.93.162.44
    port: 5672
    virtual-host: /
    username: developer01
    password: dev123456!

eureka:
  client:
    service-url:
      defaultZone: http://47.93.162.44:8761/eureka/
  instance:
    instance-id: opwe-open-service
    prefer-ip-address: true

#mybatis:
#  # mybatis配置文件所在位置
#  config-location: classpath:mybatis-config.xml
#  # mapper配置文件所在位置
#  mapper-locations: classpath:mapper/*.xml
#  # 实体类所在的位置
#  type-aliases-package: com.ljl.opweOpenService.entity

SnowFlake:
  computerRoomId: 1
  machineId: 1

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ljl.opweOpenService.entity

minio:
  url: http://47.93.162.44
  accessKey: gREgRD1Ds4PTqBA0hgzX
  secretKey: 8UVPVywcpzMvm7yyg1squjPiLUqolirn9QJ8Stiv