server:
  port: 8088

spring:
  application:
    name: opwe-data-process-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.41.70:8848
  rabbitmq:
    host: 47.93.162.44
    port: 5672
    virtual-host: /
    username: glenn
    password: dev123456!
#eureka:
#  client:
#    service-url:
#      default-zone: http://127.0.0.1:8761/eureka
#  instance:
##    instance-id: opweDataProcessService01
#    prefer-ip-address: true
