server:
  port: 8090

spring:
  application:
    name: opwe-gateway-service
  datasource:
    username: postgres #developer01 #admin
    password: dev123456!
    url: jdbc:postgresql://101.200.41.70/opwe_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    hikari:
      #minimum idle time ,default 10，less than 0 or greater than maximum-pool-size will be reset to maximum-pool-siz
      minimum-idle: 5
      #less than or equal to 0 will be reset to default value of 10；greater than 0 and less than 1 will be reset to minimum-idle
      maximum-pool-size: 10
      max-lifetime: 300000
      idle-timeout: 180000
      connection-timeout: 30000
  cloud:
    #gateway settings
    gateway:
      ## 路由
      routes:
        ## id只要唯一即可，名称任意
        - id: opwe-auth-service
          uri: lb://opwe-auth-service
          predicates:
            ## Path Route Predicate Factory断言
            - Path=/auth/**
        - id: opwe-user-service
          uri: lb://opwe-user-service
          predicates:
            ## Path Route Predicate Factory断言
            - Path=/userService/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

        config:
          enabled: true
          discovery:
            enabled: true
          discovery-service-id: config-server
#  instance:
#    instance-id: opweOpenService01
#    prefer-ip-address: true

eureka:
  client:
    service-url:
      defaultZone: http://47.93.162.44:8761/eureka/
  instance:
    instance-id: opwe-gateway-service
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        request-interceptor: com.ljl.opweGatewayService.interceptor.FeignClientInterceptor;
#oauth2:
#  cloud:
#    sys:
#      parameter:
#        ignoreUrls:
#          - /oauth/token
#          - /oauth/authorize